/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdesk;
import static helpdesk.Abierto.kk;
import static helpdesk.AbiertoUser.kk;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ferna
 */
public class cerradosUser extends javax.swing.JFrame {

    /**
     * Creates new form cerrados
     */  public static String kk;
    public cerradosUser() {
        initComponents();
        setLocationRelativeTo(null);
         Login objeto1=new Login();
        
      kk= objeto1.mail;
        mostrardatos(kk);
    }
  void mostrardatos(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Fecha");
    modelo.addColumn("Correo");
    modelo.addColumn("Nombre");
    modelo.addColumn("Carrera");
    modelo.addColumn("Cuatrimestre");
    modelo.addColumn("Departamento");
    modelo.addColumn("Tema");
    modelo.addColumn("Problema");
    modelo.addColumn("Solucion");
    modelo.addColumn("FechaC");
    
    tbproductos.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM cerrado";
    }
    else{
        sql="SELECT * FROM cerrado WHERE correo='"+valor+"'";
    }
 
    String []datos = new String [12];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                datos[9] = rs.getString(10);
                datos[10] = rs.getString(11);
                modelo.addRow(datos);
            }
            tbproductos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Abierto.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        abiertos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reabrir = new javax.swing.JTextField();
        reop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abiertos.setBackground(new java.awt.Color(204, 191, 148));
        abiertos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Abiertos-Boton1.png"))); // NOI18N
        abiertos.setBorder(null);
        abiertos.setContentAreaFilled(false);
        abiertos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        abiertos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Abiertos-Boton2.png"))); // NOI18N
        abiertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abiertosActionPerformed(evt);
            }
        });
        jPanel1.add(abiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 472, 130, 40));

        jButton2.setBackground(new java.awt.Color(204, 191, 148));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Expirados-Boton1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Expirados-Boton2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 472, -1, 40));

        reabrir.setText("ID");
        jPanel1.add(reabrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 147, -1));

        reop.setBackground(new java.awt.Color(204, 191, 148));
        reop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Re_Abrir-Boton1.png"))); // NOI18N
        reop.setBorder(null);
        reop.setContentAreaFilled(false);
        reop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Re_Abrir-Boton2.png"))); // NOI18N
        jPanel1.add(reop, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 160, 40));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 99, 25));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrados.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 620, 92));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HelpdeskA.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 11, 770, 194));

        tbproductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbproductos.setForeground(new java.awt.Color(153, 111, 39));
        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbproductos.setSelectionBackground(new java.awt.Color(204, 195, 151));
        jScrollPane1.setViewportView(tbproductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 223, 803, 211));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        expirados objeto = new expirados();
        objeto.setLocationRelativeTo(objeto);
        objeto.setVisible(true);
         this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void abiertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abiertosActionPerformed
        // TODO add your handling code here:
        AbiertoUser objeto=new AbiertoUser();
        objeto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_abiertosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cerradosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cerradosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cerradosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cerradosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cerradosUser().setVisible(true);
            }
        });
    }
 conectar cc= new conectar();
    Connection cn= cc.conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abiertos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reabrir;
    private javax.swing.JButton reop;
    private javax.swing.JTable tbproductos;
    // End of variables declaration//GEN-END:variables
}
