/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdesk;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class Estatus extends javax.swing.JFrame {

    /**
     * Creates new form Estatus
     */
    public static String Mail;
    public static String Correo;
    public static String asign;
    public static String ID;
 public Estatus() {
        initComponents();
        
        Abierto objeto= new Abierto();
    identificacion.setText(objeto.Dato);
    ID=objeto.Dato;
    
    asign=objeto.kk;
   mostrardatos("");
   mostrardatos1(ID); 
    }
 void mostrardatos1(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Fecha");
    modelo.addColumn("Respuesta");
    modelo.addColumn("Respondio");
    tbproductos.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM abierto";
    }
    else{
        sql="SELECT * FROM respuestas WHERE ID='"+valor+"'";
    }
 
    String []datos = new String [3];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(3);
                datos[1]=rs.getString(4);
                datos[2]=rs.getString(5);
                modelo.addRow(datos);
            }
            tbproductos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Abierto.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
      void mostrardatos(String valor){
    String sql="";
    String id=identificacion.getText();
    if(valor.equals(""))
    {
        sql="SELECT * FROM abierto WHERE ID= '"+id+"'";
    }
    else{
        sql="SELECT * FROM productos WHERE codigo='"+valor+"'";
    }
 String almacenamiento;
        try {
             String []datos = new String [10];
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                Fecha.setText(rs.getString(2));
                datos[2]=rs.getString(3);
                correo.setText(rs.getString(3));
                datos[3] = rs.getString(4);
                nombre.setText(rs.getString(4));
                datos[4]=rs.getString(5);
                cuatrimestre.setText(rs.getString(5));
                datos[5]=rs.getString(6);
                carrera.setText(rs.getString(6));
                datos[6]=rs.getString(7);
                departamento.setText(rs.getString(7));
                datos[7] = rs.getString(8);
                asignado.setText(rs.getString(8));
               datos[8] = rs.getString(9);
                tema.setText(rs.getString(9));  
               datos[9] = rs.getString(10);
                problem.setText(rs.getString(9));
            }
            
         
        } catch (SQLException ex) {
            Logger.getLogger(Abierto.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        correo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();
        asignado = new javax.swing.JLabel();
        problema = new javax.swing.JLabel();
        problem = new javax.swing.JLabel();
        identificacion = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        cuatrimestre = new javax.swing.JLabel();
        departamento = new javax.swing.JLabel();
        tema = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();
        close = new javax.swing.JButton();
        answer = new javax.swing.JButton();
        regreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correo.setText("Correo:");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 107, -1, -1));

        nombre.setText("Nombre:");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 132, -1, -1));

        carrera.setText("Carrera:");
        jPanel1.add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 157, -1, -1));

        asignado.setText("Asignado:");
        jPanel1.add(asignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 182, -1, -1));

        problema.setText("Problema:");
        jPanel1.add(problema, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 214, -1, -1));

        problem.setText("Correo:");
        jPanel1.add(problem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, 565, 73));

        identificacion.setText("ID:");
        jPanel1.add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 37, -1, -1));

        Fecha.setText("Fecha:");
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 69, -1, -1));

        cuatrimestre.setText("Cuatrimestre:");
        jPanel1.add(cuatrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 132, -1, -1));

        departamento.setText("Departamento:");
        jPanel1.add(departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 157, -1, -1));

        tema.setText("Tema:");
        jPanel1.add(tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 194, -1, -1));

        tbproductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbproductos.setForeground(new java.awt.Color(153, 111, 39));
        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbproductos.setGridColor(new java.awt.Color(153, 102, 0));
        tbproductos.setSelectionBackground(new java.awt.Color(204, 195, 151));
        tbproductos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbproductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, 547, 125));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564399-close_81512.png"))); // NOI18N
        close.setText("Cerrar");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 481, -1, -1));

        answer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/email_reply_15033.png"))); // NOI18N
        answer.setText("Responder ");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        regreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresar-Boton1.png"))); // NOI18N
        regreso.setContentAreaFilled(false);
        regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresoActionPerformed(evt);
            }
        });
        jPanel1.add(regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 481, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
     Window ventana = new Window();
     Correo=correo.getText();
     Mail=correo.getText();   
     ventana.Username = "HelpdeskUPQROO@gmail.com";
        ventana.PassWord = "sopademacaco123";
        ventana.To=correo.getText();
        
        ventana.Subject=tema.getText();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_answerActionPerformed

    private void regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresoActionPerformed
        // TODO add your handling code here:
        Abierto objeto=new Abierto();  
          objeto.setLocationRelativeTo(objeto);
          objeto.setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_regresoActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        try {
            Calendar cal=Calendar.getInstance(); 
String date=cal.get(cal.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
        PreparedStatement pst = cn.prepareStatement("INSERT INTO cerrado(ID, Fecha,correo,Nombres,Carrera,Cuatrimestre, Departamento, Asignado, Tema, Problema, FechaC) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
        pst.setString(1, identificacion.getText());
         pst.setString(2, Fecha.getText());
        pst.setString(3, correo.getText());
        pst.setString(4, (String) nombre.getText());
      pst.setString(5, (String) carrera.getText());
      pst.setString(6, (String) cuatrimestre.getText());
      pst.setString(7, (String) departamento.getText());
      pst.setString(8, (String) asignado.getText());
      pst.setString(9, tema.getText());
       pst.setString(10, problema.getText());
       pst.setString(11, date);
        pst.executeUpdate();
    } catch (Exception e) {
        System.out.print(e.getMessage());
    }
        String SQL="";
   
        SQL="DELETE FROM abierto WHERE ID='"+identificacion.getText()+"' ";
        try {
      PreparedStatement preparedStmt = cn.prepareStatement(SQL);
      preparedStmt.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Estatus.class.getName()).log(Level.SEVERE, null, ex);
        }
            
         JOptionPane.showMessageDialog(null, "Ticket Cerrado de manera Correcta", 
"Listo...", JOptionPane.INFORMATION_MESSAGE);
     
        
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estatus().setVisible(true);
            }
        });
    }
  conectar cc= new conectar();
    Connection cn= cc.conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton answer;
    private javax.swing.JLabel asignado;
    private javax.swing.JLabel carrera;
    private javax.swing.JButton close;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel cuatrimestre;
    private javax.swing.JLabel departamento;
    private javax.swing.JLabel identificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel problem;
    private javax.swing.JLabel problema;
    private javax.swing.JButton regreso;
    private javax.swing.JTable tbproductos;
    private javax.swing.JLabel tema;
    // End of variables declaration//GEN-END:variables
}
