/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdesk;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class EstatusUser extends javax.swing.JFrame {

    /**
     * Creates new form Estatus
     */
    public static String Mail;
    public static String Correo;
    public static String asign;
    public static String ID;
 public EstatusUser() {
        initComponents();
        
        AbiertoUser objeto= new AbiertoUser();
    identificacion.setText(objeto.Dato);
    ID=objeto.Dato;
    
    asign=objeto.kk;
   mostrardatos("");
   mostrardatos1(ID); 
    }
 void mostrardatos1(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Fecha");
    modelo.addColumn("Respuesta");
    modelo.addColumn("Respondio");
    tbproductos.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM abierto";
    }
    else{
        sql="SELECT * FROM respuestas WHERE ID='"+valor+"'";
    }
 
    String []datos = new String [3];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(3);
                datos[1]=rs.getString(4);
                datos[2]=rs.getString(5);
                modelo.addRow(datos);
            }
            tbproductos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Abierto.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
      void mostrardatos(String valor){
    String sql="";
    String id=identificacion.getText();
    if(valor.equals(""))
    {
        sql="SELECT * FROM abierto WHERE ID= '"+id+"'";
    }
    else{
        sql="SELECT * FROM productos WHERE codigo='"+valor+"'";
    }
 String almacenamiento;
        try {
             String []datos = new String [10];
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                Fecha.setText(rs.getString(2));
                datos[2]=rs.getString(3);
                correo.setText(rs.getString(3));
                datos[3] = rs.getString(4);
                nombre.setText(rs.getString(4));
                datos[4]=rs.getString(5);
                cuatrimestre.setText(rs.getString(5));
                datos[5]=rs.getString(6);
                carrera.setText(rs.getString(6));
                datos[6]=rs.getString(7);
                departamento.setText(rs.getString(7));
                datos[7] = rs.getString(8);
                asignado.setText(rs.getString(8));
               datos[8] = rs.getString(9);
                tema.setText(rs.getString(9));  
               datos[9] = rs.getString(10);
                problem.setText(rs.getString(9));
            }
            
         
        } catch (SQLException ex) {
            Logger.getLogger(Abierto.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificacion = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        cuatrimestre = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();
        departamento = new javax.swing.JLabel();
        asignado = new javax.swing.JLabel();
        tema = new javax.swing.JLabel();
        problema = new javax.swing.JLabel();
        problem = new javax.swing.JLabel();
        answer = new javax.swing.JButton();
        regreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        identificacion.setText("ID");
        getContentPane().add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 19, -1, -1));

        Fecha.setText("Fecha");
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 44, -1, -1));

        correo.setText("Correo");
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));

        nombre.setText("Nombre");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, -1, -1));

        cuatrimestre.setText("Cuatrimestre");
        getContentPane().add(cuatrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 89, -1, -1));

        carrera.setText("Carrera");
        getContentPane().add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        departamento.setText("Departamento");
        getContentPane().add(departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 109, -1, -1));

        asignado.setText("Asignado");
        getContentPane().add(asignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, -1));

        tema.setText("Tema");
        getContentPane().add(tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 129, -1, -1));

        problema.setText("Problema");
        getContentPane().add(problema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        problem.setText("Correo");
        getContentPane().add(problem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 381, 73));

        answer.setText("Responder ");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 419, -1, -1));

        regreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresar-Boton1.png"))); // NOI18N
        regreso.setContentAreaFilled(false);
        regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresoActionPerformed(evt);
            }
        });
        getContentPane().add(regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 419, -1, -1));

        tbproductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbproductos.setForeground(new java.awt.Color(153, 111, 39));
        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbproductos.setGridColor(new java.awt.Color(153, 102, 0));
        tbproductos.setSelectionBackground(new java.awt.Color(204, 195, 151));
        tbproductos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbproductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 381, 125));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
     Window ventana = new Window();
     Correo=correo.getText();
     Mail=correo.getText();   
     ventana.Username = "HelpdeskUPQROO@gmail.com";
        ventana.PassWord = "sopademacaco123";
        ventana.To=correo.getText();
        
        ventana.Subject=tema.getText();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_answerActionPerformed

    private void regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresoActionPerformed
        // TODO add your handling code here:
        AbiertoUser objeto=new AbiertoUser();  
          objeto.setLocationRelativeTo(objeto);
          objeto.setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_regresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstatusUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstatusUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstatusUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstatusUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstatusUser().setVisible(true);
            }
        });
    }
  conectar cc= new conectar();
    Connection cn= cc.conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton answer;
    private javax.swing.JLabel asignado;
    private javax.swing.JLabel carrera;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel cuatrimestre;
    private javax.swing.JLabel departamento;
    private javax.swing.JLabel identificacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel problem;
    private javax.swing.JLabel problema;
    private javax.swing.JButton regreso;
    private javax.swing.JTable tbproductos;
    private javax.swing.JLabel tema;
    // End of variables declaration//GEN-END:variables
}
