/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdesk;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class Estatus extends javax.swing.JFrame {

    /**
     * Creates new form Estatus
     */
    public static String Mail;
    public static String Correo;
    
 public Estatus() {
        initComponents();
        Abierto objeto= new Abierto();
    identificacion.setText(objeto.Dato);
   mostrardatos("");
    
    }
      void mostrardatos(String valor){
    String sql="";
    String id=identificacion.getText();
    if(valor.equals(""))
    {
        sql="SELECT * FROM abierto WHERE ID= '"+id+"'";
    }
    else{
        sql="SELECT * FROM productos WHERE codigo='"+valor+"'";
    }
 String almacenamiento;
        try {
             String []datos = new String [10];
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                Fecha.setText(rs.getString(2));
                datos[2]=rs.getString(3);
                correo.setText(rs.getString(3));
                datos[3] = rs.getString(4);
                nombre.setText(rs.getString(4));
                datos[4]=rs.getString(5);
                cuatrimestre.setText(rs.getString(5));
                datos[5]=rs.getString(6);
                carrera.setText(rs.getString(6));
                datos[6]=rs.getString(7);
                departamento.setText(rs.getString(7));
                datos[7] = rs.getString(8);
                asignado.setText(rs.getString(8));
               datos[8] = rs.getString(9);
                tema.setText(rs.getString(9));  
               datos[9] = rs.getString(10);
                problem.setText(rs.getString(9));
            }
            
         
        } catch (SQLException ex) {
            Logger.getLogger(Abierto.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificacion = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        cuatrimestre = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();
        departamento = new javax.swing.JLabel();
        asignado = new javax.swing.JLabel();
        tema = new javax.swing.JLabel();
        problema = new javax.swing.JLabel();
        problem = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        answer = new javax.swing.JButton();
        regreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        identificacion.setText("ID");

        Fecha.setText("Fecha");

        correo.setText("Correo");

        nombre.setText("Nombre");

        cuatrimestre.setText("Cuatrimestre");

        carrera.setText("Carrera");

        departamento.setText("Departamento");

        asignado.setText("Asignado");

        tema.setText("Tema");

        problema.setText("Problema");

        problem.setText("Correo");

        close.setText("Cerrar");

        answer.setText("Responder ");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        regreso.setText("Regresar");
        regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresoActionPerformed(evt);
            }
        });

        tbproductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbproductos.setForeground(new java.awt.Color(153, 111, 39));
        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbproductos.setGridColor(new java.awt.Color(153, 102, 0));
        tbproductos.setSelectionBackground(new java.awt.Color(204, 195, 151));
        tbproductos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbproductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correo)
                            .addComponent(nombre)
                            .addComponent(carrera)
                            .addComponent(asignado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuatrimestre)
                            .addComponent(Fecha)
                            .addComponent(identificacion)
                            .addComponent(departamento)
                            .addComponent(tema))
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(problema)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(close)
                                .addGap(18, 18, 18)
                                .addComponent(answer)
                                .addGap(111, 111, 111)
                                .addComponent(regreso))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(problem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(identificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fecha)
                .addGap(11, 11, 11)
                .addComponent(correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(cuatrimestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carrera)
                    .addComponent(departamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(asignado)
                    .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(problema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(problem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close)
                    .addComponent(answer)
                    .addComponent(regreso))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
     Window ventana = new Window();
     Correo=correo.getText();
     Mail=correo.getText();   
     ventana.Username = "HelpdeskUPQROO@gmail.com";
        ventana.PassWord = "sopademacaco123";
        ventana.To=correo.getText();
        
        ventana.Subject=tema.getText();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_answerActionPerformed

    private void regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresoActionPerformed
        // TODO add your handling code here:
        Abierto objeto=new Abierto();  
          objeto.setLocationRelativeTo(objeto);
          objeto.setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_regresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estatus().setVisible(true);
            }
        });
    }
  conectar cc= new conectar();
    Connection cn= cc.conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton answer;
    private javax.swing.JLabel asignado;
    private javax.swing.JLabel carrera;
    private javax.swing.JButton close;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel cuatrimestre;
    private javax.swing.JLabel departamento;
    private javax.swing.JLabel identificacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel problem;
    private javax.swing.JLabel problema;
    private javax.swing.JButton regreso;
    private javax.swing.JTable tbproductos;
    private javax.swing.JLabel tema;
    // End of variables declaration//GEN-END:variables
}
